version: '3.3'

services:
  
  redmine:
    image: redmine
    restart: always
    ports:
    - 3000:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    
  web:
    image: nginx
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl:/etc/ssl
    ports:
      - "80:80"
      - "443:443"
    links:
      - redmine
    environment:
      - NGINX_HOST=mrdudov.ru
      - NGINX_PORT=80
