version: '3.8'

services:

  proxy:
    image: nginx
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl:/etc/ssl
    networks:
      - backend
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=mrdudov.ru
      - NGINX_PORT=80

networks:
  backend:
    external:
      name: backend_default
