version: '3.3'

services:
  web:
    image: nginx
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl:/etc/ssl
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=mrdudov.ru
      - NGINX_PORT=80
